##### hydra
hydra:
    run:
      dir: ./outputs/${exp_name}/${status}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    sweep:
      dir: ./outputs/${exp_name}/${status}/${now:%Y-%m-%d}_${now:%H-%M-%S}
      subdir: ${hydra.job.override_dirname}

##### dir
exp_name: code_dev/infwide  # experiment name
tester_name: infwide_tester # tester name
status: simuexp             # run status: train|test|debug|simuexp|realexp
checkpoint: ${hydra:runtime.cwd}/model_zoo/infwide/model_infwide.pth    # loading checkpoint (${hydra:runtime.cwd})
outputs_dir: outputs/

##### run
gpus: [3]            # GPU used, Warning: Only one GPU is supported for 'test' now
num_workers: 16      # number of cpu worker

##### arch
network_name: infwide
arch:
  _target_: srcs.model.infwide_model.infwide
  n_colors: 3
  input_denoise: ResUnet 

##### metrics
metrics:
  - _target_: srcs.metric._metric.calc_psnr
  - _target_: srcs.metric._metric.calc_ssim

##### data&nets
defaults:
  - data: infwide_exp_data      # infwide_test_data | infwide_exp_data
  - override hydra/job_logging : custom # custom | colorlog
  - override hydra/hydra_logging: colorlog
  - _self_